server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-80

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname:  ${spring.application.name}
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

