server:
  port: 7001


spring:
  application:
    name: eureka7001.com
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  instance:
    instance-id: ${spring.application.name}
    hostname:  ${spring.application.name}  #eureka服务端的实例名字
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
#      defaultZone: http://${eureka.instance.hostname}:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
